server:
  port: 8082

spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/shop
    username: hobin
    password: zaq12wsx

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6379

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 4   # 실패 4% 이상 시 서킷 오픈
        slow-call-duration-threshold: 3000   # 500ms 이상 소요 시 실패로 간주
        slow-call-rate-threshold: 4   # slowCallDurationThreshold 초과 비율이 10% 이상 시 서킷 오픈
        wait-duration-in-open-state: 6000   # OPEN -> HALF-OPEN 전환 전 기다리는 시간
        minimum-number-of-calls: 50   # 집계에 필요한 최소 호출 수
        sliding-window-size: 100   # 서킷 CLOSE 상태에서 N회 호출 도달 시 failureRateThreshold 실패 비율 계산
        permitted-number-of-calls-in-half-open-state: 10   # HALFOPEN -> CLOSE or OPEN 으로 판단하기 위해 호출 횟수
    instances:
      order-service:
        base-config: default
  retry:
    configs:
      default:
        wait-duration: 100   # 재시도 사이 간격
        max-attempts: 2   # 재시도 횟수(최초 호출 포함)
    instances:
      order-service:
        base-config: default

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace