server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway-service
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/api/products/**
            - Method=GET
          filters:
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/**
          filters:
            - RewritePath=/payment-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/auth/users/email
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/auth/users/email/verify
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/auth/users/signup
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/auth/users/login
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/auth/users/**
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/api/users/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

env:
  token:
    secret: sherpaprojectforclimbingshoppingmallshop